export const mandalas=[
 {slug:"oceano",title:"Mandala del océano",short:"Conchas y estrellas de mar",description:"Conchas, corales, olas y estrellas de mar forman una lámina fresca de dificultad media inspirada en la costa.",image:"/mandalas/mandala-botanico.webp"},
 {slug:"floral-facil",title:"Mandala floral fácil",short:"Pétalos grandes y hojas",description:"Un mandala fácil con pétalos amplios, hojas sencillas y grandes espacios para colorear sin prisas.",image:"/mandalas/mandala-petalos-hojas.webp"},
 {slug:"circulos-y-hojas",title:"Mandala de círculos y hojas",short:"Geometría suave",description:"Círculos entrelazados y una corona ligera de hojas combinan orden geométrico y naturaleza.",image:"/mandalas/mandala-circulos-florales.webp"},
 {slug:"loto-facil",title:"Mandala de loto fácil",short:"Dos anillos de pétalos",description:"Una flor de loto simétrica con pétalos anchos y pocos elementos, pensada para colorear con comodidad.",image:"/mandalas/mandala-loto-geometrico.webp"},
 {slug:"estrella-botanica",title:"Mandala de estrella botánica",short:"Puntas y hojas",description:"Una estrella de ocho puntas suavizada con hojas grandes y líneas limpias de inspiración botánica.",image:"/mandalas/mandala-estrella-botanica.webp"},
 {slug:"sol-floral",title:"Mandala de sol y pétalos",short:"Radial y luminoso",description:"Un centro solar rodeado de pétalos amplios y una corona de hojas, con una dificultad fácil y equilibrada.",image:"/mandalas/mandala-sol-petalos.webp"},
 {slug:"rosa-geometrica",title:"Mandala de rosa geométrica",short:"Rosa y hojas simétricas",description:"Una rosa vista desde arriba combina pétalos amplios con una corona de hojas ordenada y fácil de colorear.",image:"/mandalas/mandala-rosa-geometrica.webp"},
 {slug:"girasol-geometrico",title:"Mandala de girasol geométrico",short:"Pétalos y centro triangular",description:"Un girasol radial de pétalos grandes con un centro geométrico y hojas sencillas alrededor.",image:"/mandalas/mandala-girasol-geometrico.webp"},
 {slug:"margaritas-radiales",title:"Mandala de margaritas",short:"Seis flores radiales",description:"Seis margaritas de líneas limpias se organizan alrededor de una pequeña estrella central.",image:"/mandalas/mandala-margaritas-radiales.webp"},
 {slug:"flores-y-hojas",title:"Mandala de flores y hojas",short:"Corona floral equilibrada",description:"Flores redondeadas y hojas amplias forman una composición botánica simétrica de dificultad media.",image:"/mandalas/mandala-flores-y-hojas.webp"},
 {slug:"flores-silvestres",title:"Mandala de flores silvestres",short:"Botánica suave",description:"Flores silvestres simplificadas y hojas alargadas crean una lámina elegante con espacios cómodos.",image:"/mandalas/mandala-flores-silvestres.webp"},
 {slug:"mariposas-florales",title:"Mandala de mariposas y flores",short:"Naturaleza simétrica",description:"Cuatro mariposas estilizadas se alternan con flores y hojas en una composición clara y armoniosa.",image:"/mandalas/mandala-mariposas-florales.webp"},
 {slug:"floral-moderado",title:"Mandala floral de dificultad media",short:"Más detalle, zonas amplias",description:"Una roseta floral de varias capas ofrece algo más de detalle sin recurrir a espacios pequeños.",image:"/mandalas/mandala-floral-moderado.webp"},
 {slug:"cuadrados-botanicos",title:"Mandala de cuadrados y hojas",short:"Geometría botánica",description:"Cuadrados entrelazados de esquinas suaves se combinan con hojas para unir orden y naturaleza.",image:"/mandalas/mandala-cuadrados-botanicos.webp"},
 {slug:"gato-floral",title:"Mandala de gato con flores",short:"Gato y corona botánica",description:"Un elegante rostro de gato aparece entre pétalos y hojas amplias en un mandala equilibrado para imprimir.",image:"/mandalas/mandala-gato-floral.webp"},
 {slug:"gato-geometrico",title:"Mandala de gato geométrico",short:"Facetas suaves y hojas",description:"Un gato de formas geométricas suaves se integra en una composición simétrica con motivos de hojas.",image:"/mandalas/mandala-gato-geometrico.webp"},
 {slug:"elefante-botanico",title:"Mandala de elefante con flores",short:"Elefante botánico",description:"La cabeza de un elefante se combina con pétalos grandes y una corona botánica de dificultad media.",image:"/mandalas/mandala-elefante-botanico.webp"},
 {slug:"buho-geometrico",title:"Mandala de búho geométrico",short:"Búho, plumas y hojas",description:"Un búho frontal de ojos circulares y plumas amplias ocupa el centro de una roseta geométrica y botánica.",image:"/mandalas/mandala-buho-geometrico.webp"},
 {slug:"mariposa-geometrica",title:"Mandala de mariposa geométrica",short:"Alas y corona de hojas",description:"Una mariposa de alas geométricas y espacios amplios aparece rodeada por una sencilla corona de hojas.",image:"/mandalas/mandala-mariposa-geometrica.webp"},
 {slug:"circulos-concentricos",title:"Mandala de círculos concéntricos",short:"Arcos, pétalos y hojas",description:"Círculos concéntricos se transforman en pétalos, arcos y hojas dentro de una composición ordenada y fácil de colorear.",image:"/mandalas/mandala-circulos-concentricos.webp"},
 {slug:"espirales-botanicas",title:"Mandala de espirales y hojas",short:"Curvas botánicas",description:"Cuatro espirales grandes se alternan con hojas y una flor central en un diseño claro de dificultad media.",image:"/mandalas/mandala-espirales-botanicas.webp"},
 {slug:"patron-floral-repetitivo",title:"Mandala de patrón floral repetitivo",short:"Ritmo geométrico floral",description:"Pétalos, rombos redondeados y hojas se repiten de forma radial para crear un mandala sereno y proporcionado.",image:"/mandalas/mandala-patron-floral-repetitivo.webp"},
 {slug:"setas-y-bosque",title:"Mandala de setas y bosque",short:"Setas, helechos y hojas",description:"Setas de bosque rodeadas de helechos y hojas en una composición natural para colorear.",image:"/mandalas/setas-y-bosque.webp"},
 {slug:"sol-y-luna",title:"Mandala de sol y luna",short:"Astros y hojas simétricas",description:"El sol y la luna se encuentran entre estrellas y hojas dentro de un diseño equilibrado.",image:"/mandalas/sol-y-luna.webp"},
 {slug:"capibara-con-flores",title:"Mandala de capibara con flores",short:"Capibara y corona floral",description:"Una tranquila capibara aparece rodeada de flores amplias en un mandala original y amable.",image:"/mandalas/capibara-con-flores.webp"},
 {slug:"faro-y-olas",title:"Mandala de faro y olas",short:"Faro, mar y costa",description:"Un faro entre olas y motivos costeros crea una lámina marinera de dificultad media.",image:"/mandalas/faro-y-olas.webp"},
 {slug:"libros-y-flores",title:"Mandala de libros y flores",short:"Lectura y jardín floral",description:"Una pila de libros se integra entre flores y hojas para disfrutar de una pausa creativa.",image:"/mandalas/libros-y-flores.webp"},
 {slug:"planetas-y-estrellas",title:"Mandala de planetas y estrellas",short:"Sistema solar geométrico",description:"Planetas, órbitas y estrellas forman una composición espacial clara y simétrica.",image:"/mandalas/planetas-y-estrellas.webp"},
 {slug:"cactus-y-suculentas",title:"Mandala de cactus y suculentas",short:"Jardín de plantas resistentes",description:"Cactus y suculentas de formas variadas componen un jardín geométrico para colorear.",image:"/mandalas/cactus-y-suculentas.webp"},
 {slug:"ajolote-floral",title:"Mandala de ajolote floral",short:"Ajolote entre flores",description:"Un ajolote de líneas suaves ocupa el centro de una alegre corona botánica.",image:"/mandalas/ajolote-floral.webp"},
 {slug:"taza-de-cafe-floral",title:"Mandala de taza de café floral",short:"Café, vapor y flores",description:"Una taza humeante rodeada de grandes flores crea una lámina acogedora y moderna.",image:"/mandalas/taza-de-cafe-floral.webp"},
 {slug:"arbol-de-la-vida",title:"Mandala del árbol de la vida",short:"Raíces y copa frondosa",description:"Raíces profundas y ramas frondosas forman un árbol de la vida simétrico para imprimir.",image:"/mandalas/arbol-de-la-vida.webp"},
 {slug:"conchas-marinas",title:"Mandala de conchas marinas",short:"Conchas y formas oceánicas",description:"Conchas, caracolas y motivos marinos se distribuyen en una composición radial ligera.",image:"/mandalas/conchas-marinas.webp"},
 {slug:"guitarra-con-flores",title:"Mandala de guitarra con flores",short:"Música y botánica",description:"Una guitarra acústica se rodea de flores y hojas en un dibujo musical equilibrado.",image:"/mandalas/guitarra-con-flores.webp"},
 {slug:"geometria-sagrada",title:"Mandala de geometría sagrada",short:"Círculos y roseta central",description:"Círculos entrelazados, pétalos y formas hexagonales crean una geometría serena.",image:"/mandalas/geometria-sagrada.webp"},
 {slug:"castillo-de-fantasia",title:"Mandala de castillo de fantasía",short:"Torres, estrellas y enredaderas",description:"Un castillo de cuento se alza entre estrellas y formas vegetales de líneas limpias.",image:"/mandalas/castillo-de-fantasia.webp"},
 {slug:"globo-aerostatico",title:"Mandala de globo aerostático",short:"Vuelo entre nubes y hojas",description:"Un globo aerostático decorado flota entre nubes dentro de una composición circular.",image:"/mandalas/globo-aerostatico.webp"},
 {slug:"abejas-y-girasoles",title:"Mandala de abejas y girasoles",short:"Abejas entre grandes flores",description:"Abejas y girasoles se combinan en una lámina luminosa inspirada en el verano.",image:"/mandalas/abejas-y-girasoles.webp"},
 {slug:"fondo-marino",title:"Mandala de fondo marino",short:"Pez, coral y algas",description:"Un pez nada entre coral, algas y burbujas en una escena submarina para colorear.",image:"/mandalas/fondo-marino.webp"},
 {slug:"casita-del-bosque",title:"Mandala de casita del bosque",short:"Casa, setas y helechos",description:"Una acogedora casita aparece entre setas, helechos y árboles dentro de una corona natural.",image:"/mandalas/casita-del-bosque.webp"},
 {slug:"mariposas-y-lavanda",title:"Mandala de mariposas y lavanda",short:"Alas y flores aromáticas",description:"Mariposas elegantes vuelan entre ramas de lavanda en un diseño botánico proporcionado.",image:"/mandalas/mariposas-y-lavanda.webp"},
 {slug:"cristales-y-estrellas",title:"Mandala de cristales y estrellas",short:"Minerales y cielo nocturno",description:"Cristales facetados se combinan con estrellas y lunas en una composición geométrica.",image:"/mandalas/cristales-y-estrellas.webp"},
 {slug:"jardin-japones",title:"Mandala de jardín japonés",short:"Puente, agua y arces",description:"Un puente curvo, una linterna y hojas de arce forman un tranquilo jardín japonés.",image:"/mandalas/jardin-japones.webp"},
 {slug:"dragon-oriental",title:"Mandala de dragón oriental",short:"Dragón, nubes y flores",description:"Un dragón oriental serpentea entre nubes y flores dentro de un marco circular.",image:"/mandalas/dragon-oriental.webp"},
 {slug:"ballena-y-oceano",title:"Mandala de ballena y océano",short:"Ballena entre olas",description:"Una ballena tranquila nada entre olas, burbujas y plantas marinas de formas amplias.",image:"/mandalas/ballena-y-oceano.webp"},
 {slug:"bicicleta-con-flores",title:"Mandala de bicicleta con flores",short:"Paseo y cesta floral",description:"Una bicicleta clásica con cesta de flores protagoniza una lámina alegre y equilibrada.",image:"/mandalas/bicicleta-con-flores.webp"},
 {slug:"casas-de-cuento",title:"Mandala de casas de cuento",short:"Casitas de tejados curvos",description:"Tres casas de cuento con tejados originales y flores crean una pequeña escena fantástica.",image:"/mandalas/casas-de-cuento.webp"},
 {slug:"luna-con-flores",title:"Mandala de luna con flores",short:"Luna creciente botánica",description:"Una gran luna creciente abraza flores y hojas bajo un sencillo cielo de estrellas.",image:"/mandalas/luna-con-flores.webp"},
 {slug:"tetera-con-flores",title:"Mandala de tetera con flores",short:"Tetera, vapor y pétalos",description:"Una tetera redonda aparece entre flores y hojas en una composición cálida para colorear.",image:"/mandalas/tetera-con-flores.webp"},
 {slug:"jardin-de-hadas",title:"Mandala de jardín de hadas",short:"Hada, flores y setas",description:"Una pequeña hada descubre un jardín de flores, setas y una puerta encantada.",image:"/mandalas/jardin-de-hadas.webp"},
 {slug:"ventana-con-plantas",title:"Mandala de ventana con plantas",short:"Ventana y macetas verdes",description:"Una ventana arqueada se rodea de plantas colgantes y macetas en una escena acogedora.",image:"/mandalas/ventana-con-plantas.webp"},
 {slug:"montanas-y-luna",title:"Mandala de montañas y luna",short:"Paisaje nocturno natural",description:"Montañas, pinos y una luna creciente forman un paisaje nocturno sereno para imprimir.",image:"/mandalas/montanas-y-luna.webp"},
] as const;

export const mandalaCategories = [
  {slug:"flores-y-naturaleza",title:"Mandalas de flores y naturaleza",short:"Flores, hojas y jardines",description:"Mandalas florales y botánicos para imprimir gratis, con pétalos amplios, hojas y composiciones naturales fáciles de colorear.",image:"/mandalas/mandala-petalos-hojas.webp",tip:"Prueba verdes suaves para las hojas y combina dos o tres tonos en los pétalos para conservar una composición tranquila."},
  {slug:"animales",title:"Mandalas de animales",short:"Gatos, aves y fauna",description:"Mandalas de animales para imprimir y colorear, desde gatos y búhos hasta elefantes, mariposas y criaturas marinas.",image:"/mandalas/mandala-gato-floral.webp",tip:"Empieza por el animal central y utiliza una gama distinta en el marco para que la figura destaque con claridad."},
  {slug:"geometricos",title:"Mandalas geométricos",short:"Círculos, espirales y simetría",description:"Mandalas geométricos para imprimir gratis con círculos, espirales y patrones simétricos de dificultad fácil y media.",image:"/mandalas/geometria-sagrada.webp",tip:"Repite una paleta corta de tres o cuatro colores siguiendo la simetría para reforzar el ritmo del diseño."},
  {slug:"paisajes-y-mar",title:"Mandalas de paisajes y mar",short:"Bosques, océano y montaña",description:"Paisajes en forma de mandala para imprimir y colorear: océanos, faros, bosques, jardines y montañas de líneas limpias.",image:"/mandalas/faro-y-olas.webp",tip:"Separa visualmente cielo, tierra y elementos naturales con familias de color diferentes y degradados sencillos."},
  {slug:"fantasia-y-espacio",title:"Mandalas de fantasía y espacio",short:"Lunas, estrellas y cuentos",description:"Mandalas de fantasía y espacio para imprimir con castillos, dragones, planetas, hadas, lunas y escenas de cuento.",image:"/mandalas/castillo-de-fantasia.webp",tip:"Combina colores profundos para el fondo con tonos luminosos en estrellas, magia y elementos protagonistas."},
  {slug:"objetos-y-hogar",title:"Mandalas de objetos y hogar",short:"Libros, música y rincones",description:"Mandalas de objetos cotidianos para imprimir: libros, tazas, instrumentos, bicicletas y rincones acogedores con flores.",image:"/mandalas/libros-y-flores.webp",tip:"Elige primero el color del objeto protagonista y utiliza tonos complementarios más suaves en las flores y adornos."},
] as const;

export type MandalaCategorySlug = typeof mandalaCategories[number]["slug"];

const categoryByMandala: Record<string, MandalaCategorySlug> = {
  oceano:"paisajes-y-mar", "floral-facil":"flores-y-naturaleza", "circulos-y-hojas":"geometricos", "loto-facil":"flores-y-naturaleza", "estrella-botanica":"geometricos", "sol-floral":"flores-y-naturaleza", "rosa-geometrica":"flores-y-naturaleza", "girasol-geometrico":"flores-y-naturaleza", "margaritas-radiales":"flores-y-naturaleza", "flores-y-hojas":"flores-y-naturaleza", "flores-silvestres":"flores-y-naturaleza", "mariposas-florales":"flores-y-naturaleza", "floral-moderado":"flores-y-naturaleza", "cuadrados-botanicos":"geometricos", "gato-floral":"animales", "gato-geometrico":"animales", "elefante-botanico":"animales", "buho-geometrico":"animales", "mariposa-geometrica":"animales", "circulos-concentricos":"geometricos", "espirales-botanicas":"geometricos", "patron-floral-repetitivo":"geometricos", "setas-y-bosque":"paisajes-y-mar", "sol-y-luna":"fantasia-y-espacio", "capibara-con-flores":"animales", "faro-y-olas":"paisajes-y-mar", "libros-y-flores":"objetos-y-hogar", "planetas-y-estrellas":"fantasia-y-espacio", "cactus-y-suculentas":"flores-y-naturaleza", "ajolote-floral":"animales", "taza-de-cafe-floral":"objetos-y-hogar", "arbol-de-la-vida":"paisajes-y-mar", "conchas-marinas":"paisajes-y-mar", "guitarra-con-flores":"objetos-y-hogar", "geometria-sagrada":"geometricos", "castillo-de-fantasia":"fantasia-y-espacio", "globo-aerostatico":"fantasia-y-espacio", "abejas-y-girasoles":"flores-y-naturaleza", "fondo-marino":"animales", "casita-del-bosque":"paisajes-y-mar", "mariposas-y-lavanda":"flores-y-naturaleza", "cristales-y-estrellas":"geometricos", "jardin-japones":"paisajes-y-mar", "dragon-oriental":"fantasia-y-espacio", "ballena-y-oceano":"animales", "bicicleta-con-flores":"objetos-y-hogar", "casas-de-cuento":"fantasia-y-espacio", "luna-con-flores":"fantasia-y-espacio", "tetera-con-flores":"objetos-y-hogar", "jardin-de-hadas":"fantasia-y-espacio", "ventana-con-plantas":"objetos-y-hogar", "montanas-y-luna":"paisajes-y-mar"
};

export function getCategoryForMandala(slug:string){const categorySlug=categoryByMandala[slug];return mandalaCategories.find(category=>category.slug===categorySlug)}
export function getMandalasByCategory(slug:string){return mandalas.filter(mandala=>categoryByMandala[mandala.slug]===slug)}
export function createMetaDescription(description:string){const suffix=" Descárgalo gratis, imprímelo en A4 y disfruta coloreándolo en casa o en clase.";const full=`${description}${suffix}`;if(full.length<=155)return full;const cut=full.slice(0,154);return `${cut.slice(0,cut.lastIndexOf(" "))}.`}
